apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["sh", "-c", "sleep infinity"]
          volumeMounts:
            - name: storage-volume
              mountPath: /mnt/data
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: storage3
